# Generator bank soal TWK batch 7. Format tiap item: (id, q, [jawaban_benar, ...pengecoh], ex)
# Script mengacak urutan opsi (seed tetap) lalu menulis js/data/twk_b7.js
import random, json

Q = [
# ===== PANCASILA 40 (901-940): penyimpangan terhadap Pancasila =====
("TWK-901","Gerakan DI/TII di Jawa Barat memproklamasikan berdirinya Negara Islam Indonesia pada tanggal ....",
 ["7 Agustus 1949","17 Agustus 1945","27 Desember 1949","17 Agustus 1950","5 Juli 1959"],
 "S.M. Kartosoewirjo memproklamasikan Negara Islam Indonesia di Cisampah, Tasikmalaya, pada 7 Agustus 1949."),
("TWK-902","Pemimpin gerakan DI/TII di Jawa Barat adalah ....",
 ["S.M. Kartosoewirjo","Daud Beureueh","Kahar Muzakkar","Ibnu Hajar","Amir Fatah"],
 "DI/TII Jawa Barat dipimpin S.M. Kartosoewirjo yang kecewa terhadap hasil Perjanjian Renville."),
("TWK-903","Pemberontakan DI/TII di Jawa Barat berakhir pada tahun 1962 setelah ....",
 ["Kartosoewirjo tertangkap di Gunung Geber","ditandatanganinya MoU Helsinki","dikeluarkannya Dekret Presiden","dibubarkannya Konstituante","dilaksanakannya Operasi Seroja"],
 "Kartosoewirjo tertangkap pada 4 Juni 1962 di Gunung Geber, Majalaya, sehingga DI/TII Jawa Barat berakhir."),
("TWK-904","Tokoh yang memimpin gerakan DI/TII di Aceh adalah ....",
 ["Daud Beureueh","Kahar Muzakkar","Ibnu Hajar","Batalyon 426","Amir Fatah"],
 "DI/TII Aceh dipimpin Teungku Daud Beureueh sejak September 1953."),
("TWK-905","Pemberontakan DI/TII di Aceh diselesaikan secara damai dan menghasilkan status Daerah Istimewa bagi Aceh melalui ....",
 ["Musyawarah Kerukunan Rakyat Aceh","Perjanjian Malino","MoU Helsinki","Konferensi Meja Bundar","Perjanjian Renville"],
 "Melalui Musyawarah Kerukunan Rakyat Aceh (1959), pemerintah memberi status Daerah Istimewa kepada Aceh sehingga Daud Beureueh kembali ke pangkuan NKRI."),
("TWK-906","Pemimpin DI/TII di Sulawesi Selatan adalah ....",
 ["Kahar Muzakkar","Andi Azis","Ventje Sumual","Ahmad Husein","Sjafruddin Prawiranegara"],
 "Abdul Kahar Muzakkar memimpin DI/TII di Sulawesi Selatan sejak 1950 hingga tewas pada 1965."),
("TWK-907","Gerakan DI/TII di Kalimantan Selatan dipimpin oleh ....",
 ["Ibnu Hajar","Kahar Muzakkar","Daud Beureueh","Kartosoewirjo","Soumokil"],
 "DI/TII Kalimantan Selatan dipimpin Ibnu Hajar pada awal 1950-an."),
("TWK-908","Gerakan separatisme seperti DI/TII yang ingin mengganti dasar negara pada dasarnya bertentangan dengan Pancasila sila ....",
 ["ketiga","pertama","kedua","keempat","kelima"],
 "Separatisme merongrong persatuan dan kesatuan bangsa sehingga bertentangan dengan sila ketiga, Persatuan Indonesia."),
("TWK-909","PRRI diproklamasikan pada 15 Februari 1958 di ....",
 ["Bukittinggi","Bandung","Makassar","Medan","Ambon"],
 "PRRI (Pemerintah Revolusioner Republik Indonesia) diproklamasikan di Padang/Bukittinggi, Sumatera Barat, pada 15 Februari 1958."),
("TWK-910","Tokoh yang diangkat sebagai Perdana Menteri PRRI adalah ....",
 ["Sjafruddin Prawiranegara","Ahmad Husein","Ventje Sumual","Soekarno","Mohammad Hatta"],
 "Sjafruddin Prawiranegara, mantan Gubernur Bank Indonesia, diangkat sebagai Perdana Menteri PRRI."),
("TWK-911","Gerakan Permesta diproklamasikan di Manado pada 2 Maret 1958 di bawah pimpinan ....",
 ["Ventje Sumual","Ahmad Husein","Sjafruddin Prawiranegara","Kahar Muzakkar","Andi Azis"],
 "Permesta (Perjuangan Semesta) diproklamasikan di Manado pada 2 Maret 1958 dipimpin Letkol Ventje Sumual."),
("TWK-912","Salah satu penyebab utama pemberontakan PRRI/Permesta adalah ....",
 ["ketidakpuasan daerah terhadap pembagian hasil pembangunan oleh pemerintah pusat","keinginan mendirikan negara Islam","pengaruh ideologi komunisme","penolakan terhadap UUD 1945","keinginan bergabung dengan Malaysia"],
 "PRRI/Permesta dipicu kekecewaan daerah atas sentralisasi kekuasaan dan ketidakadilan pembagian hasil devisa serta pembangunan."),
("TWK-913","Dewan Banteng yang menjadi cikal bakal PRRI dibentuk di Sumatera Barat di bawah pimpinan ....",
 ["Ahmad Husein","Sjafruddin Prawiranegara","Ventje Sumual","Dahlan Djambek","Ismail Lengah"],
 "Dewan Banteng dibentuk di Padang pada Desember 1956 dipimpin Letkol Ahmad Husein sebagai protes terhadap pemerintah pusat."),
("TWK-914","Pemberontakan PRRI/Permesta yang menentang pemerintah yang sah bertentangan dengan Pancasila sila ....",
 ["ketiga","pertama","kedua","keempat","kelima"],
 "Pemberontakan bersenjata terhadap pemerintah yang sah merusak persatuan nasional sehingga bertentangan dengan sila ketiga."),
("TWK-915","Gerakan 30 September dilancarkan oleh sekelompok perwira pada ....",
 ["malam 30 September 1965","pagi 1 Oktober 1966","17 Agustus 1965","11 Maret 1966","1 Juni 1965"],
 "G30S dilancarkan pada malam 30 September hingga dini hari 1 Oktober 1965 dengan menculik dan membunuh para jenderal TNI AD."),
("TWK-916","Pemimpin lapangan Gerakan 30 September 1965 adalah ....",
 ["Letkol Untung Syamsuri","D.N. Aidit","Sjam Kamaruzaman","Kolonel Latief","Mayjen Soeharto"],
 "G30S dipimpin Letkol Untung Syamsuri, komandan Batalyon I Resimen Cakrabirawa."),
("TWK-917","Melalui siaran RRI, G30S mengumumkan telah membentuk ....",
 ["Dewan Revolusi","Dewan Jenderal","Dewan Pertimbangan Agung","Front Nasional","Komite Revolusi"],
 "G30S mengumumkan pembentukan Dewan Revolusi Indonesia yang diketuai Letkol Untung sebagai pengganti pemerintahan."),
("TWK-918","G30S melancarkan aksinya dengan mengembuskan isu adanya ....",
 ["Dewan Jenderal yang akan mengkudeta Presiden","penyerbuan Belanda ke Irian Barat","pemberontakan DI/TII di Jawa Barat","rencana pemilihan umum 1971","konflik Indonesia dengan Malaysia"],
 "G30S menyebarkan isu Dewan Jenderal yang disebut akan mengkudeta Soekarno sebagai dalih penculikan para jenderal."),
("TWK-919","Jumlah perwira TNI AD yang gugur dalam peristiwa G30S dan dinobatkan sebagai Pahlawan Revolusi adalah ....",
 ["7 orang","5 orang","6 orang","8 orang","9 orang"],
 "Tujuh perwira gugur: enam jenderal (Ahmad Yani, Suprapto, Haryono, Parman, Panjaitan, Sutoyo) dan satu perwira pertama (Pierre Tendean)."),
("TWK-920","Tokoh militer yang menjadi target penculikan G30S tetapi berhasil lolos adalah ....",
 ["A.H. Nasution","Ahmad Yani","M.T. Haryono","S. Parman","Sutoyo Siswomiharjo"],
 "Menko Hankam/Kasab A.H. Nasution berhasil lolos dengan memanjat tembok, meski putrinya Ade Irma Suryani gugur."),
("TWK-921","Jenazah para Pahlawan Revolusi ditemukan di sebuah sumur tua di daerah ....",
 ["Lubang Buaya, Jakarta Timur","Kalibata, Jakarta Selatan","Bogor, Jawa Barat","Semarang, Jawa Tengah","Surabaya, Jawa Timur"],
 "Ketujuh jenazah ditemukan pada 3 Oktober 1965 di sumur tua Lubang Buaya, Jakarta Timur, lalu dimakamkan di TMP Kalibata."),
("TWK-922","Anggota Polri yang berhasil lolos dari upaya penculikan G30S dan menjadi saksi kunci adalah ....",
 ["Sukitman","Karel Satsuit Tubun","Pierre Tendean","Ade Irma Suryani","Soegandhi"],
 "Agen Polisi Sukitman berhasil meloloskan diri dari penculikan di rumah A.H. Nasution dan memberi kesaksian penting."),
("TWK-923","Operasi penumpasan G30S dipimpin oleh .... yang saat itu menjabat Pangkostrad.",
 ["Soeharto","A.H. Nasution","Sarwo Edhie Wibowo","Umar Wirahadikusumah","M. Jusuf"],
 "Mayjen Soeharto selaku Pangkostrad mengambil alih pimpinan TNI AD dan memimpin penumpasan G30S."),
("TWK-924","Surat Perintah Sebelas Maret dikeluarkan Presiden Soekarno pada tanggal ....",
 ["11 Maret 1966","11 Maret 1965","30 September 1965","1 Oktober 1965","5 Juli 1959"],
 "Supersemar ditandatangani Soekarno di Istana Bogor pada 11 Maret 1966 dan diserahkan kepada Letjen Soeharto."),
("TWK-925","Melalui Supersemar, Presiden Soekarno memerintahkan Letjen Soeharto untuk ....",
 ["mengambil segala tindakan yang dianggap perlu untuk menjamin keamanan dan kestabilan jalannya pemerintahan","membubarkan DPR hasil pemilu 1955","menangkap seluruh anggota MPRS","menyelenggarakan pemilihan umum","membentuk Dewan Revolusi"],
 "Supersemar memberi mandat kepada Soeharto untuk memulihkan keamanan dan ketertiban pasca-G30S."),
("TWK-926","Ketetapan yang membubarkan PKI dan melarang ajaran Marxisme-Leninisme di Indonesia adalah ....",
 ["TAP MPRS No. XXV/MPRS/1966","TAP MPRS No. III/MPRS/1963","TAP MPR No. II/MPR/1978","TAP MPR No. IV/MPR/1973","Keppres No. 1/PNPS/1965"],
 "TAP MPRS No. XXV/MPRS/1966 membubarkan PKI sebagai organisasi terlarang dan melarang penyebaran paham komunisme/Marxisme-Leninisme."),
("TWK-927","Pemberontakan G30S/PKI yang berideologi komunis pada hakikatnya bertentangan dengan Pancasila sila ....",
 ["pertama","kedua","ketiga","keempat","kelima"],
 "Komunisme yang ateis dan menolak Ketuhanan bertentangan dengan sila pertama, Ketuhanan Yang Maha Esa."),
("TWK-928","Republik Maluku Selatan diproklamasikan oleh Dr. Soumokil pada tanggal ....",
 ["25 April 1950","27 Desember 1949","17 Agustus 1950","5 April 1950","15 Februari 1958"],
 "RMS diproklamasikan Dr. Chr. Soumokil di Ambon pada 25 April 1950 dan ditumpas melalui operasi militer."),
("TWK-929","Pemberontakan Andi Azis di Makassar terjadi pada tanggal ....",
 ["5 April 1950","25 April 1950","7 Agustus 1949","15 Februari 1958","30 September 1965"],
 "Andi Azis, mantan perwira KNIL, melancarkan pemberontakan di Makassar pada 5 April 1950 menentang APRIS."),
("TWK-930","Konsep Nasakom yang digagas Presiden Soekarno dinilai menyimpang dari Pancasila karena ....",
 ["menempatkan komunisme yang bertentangan dengan Ketuhanan sejajar dengan nasionalisme dan agama","menolak musyawarah mufakat","menghapus sila Persatuan Indonesia","meniadakan pemilihan umum","mengganti UUD 1945"],
 "Nasakom (Nasionalisme, Agama, Komunisme) menyimpang karena komunisme yang ateis tidak sejalan dengan sila pertama Pancasila."),
("TWK-931","Pengangkatan Soekarno sebagai presiden seumur hidup melalui TAP MPRS No. III/MPRS/1963 dinilai menyimpang dari Pancasila sila ....",
 ["keempat","pertama","kedua","ketiga","kelima"],
 "Presiden seumur hidup meniadakan pergantian kepemimpinan yang demokratis sehingga bertentangan dengan sila keempat tentang kerakyatan dan permusyawaratan."),
("TWK-932","Dekret Presiden 5 Juli 1959 dinilai sebagai upaya penyelamatan negara karena ....",
 ["mengembalikan UUD 1945 dan menghentikan kemacetan konstitusi era demokrasi liberal","membubarkan PKI","menetapkan Pancasila sebagai satu-satunya asas","menasionalisasi perusahaan Belanda","menyelenggarakan pemilihan umum"],
 "Dekret 5 Juli 1959 membubarkan Konstituante yang gagal membuat konstitusi dan memberlakukan kembali UUD 1945."),
("TWK-933","Pedoman Penghayatan dan Pengamalan Pancasila (P4) ditetapkan melalui ....",
 ["TAP MPR No. II/MPR/1978","TAP MPRS No. XXV/MPRS/1966","TAP MPR No. IV/MPR/1973","TAP MPRS No. III/MPRS/1963","UU No. 5 Tahun 1985"],
 "P4 atau Ekaprasetia Pancakarsa ditetapkan melalui TAP MPR No. II/MPR/1978 sebagai penuntun pengamalan Pancasila."),
("TWK-934","Paham yang menghendaki pendirian negara khilafah dan menolak Pancasila sebagai dasar negara dikategorikan sebagai ....",
 ["radikalisme","liberalisme","sosialisme","nasionalisme","federalisme"],
 "Paham khilafah yang menolak Pancasila dan NKRI termasuk radikalisme yang mengancam ideologi negara."),
("TWK-935","Aksi terorisme yang menghilangkan nyawa orang tidak bersalah bertentangan dengan Pancasila sila ....",
 ["kedua","pertama","ketiga","keempat","kelima"],
 "Terorisme merampas hak hidup manusia sehingga bertentangan dengan sila kedua, Kemanusiaan yang adil dan beradab."),
("TWK-936","Tindakan intoleransi dan pemaksaan keyakinan agama kepada orang lain bertentangan dengan Pancasila sila ....",
 ["pertama","kedua","ketiga","keempat","kelima"],
 "Sila pertama menjamin kebebasan beragama dan melarang pemaksaan suatu agama kepada orang lain."),
("TWK-937","Praktik korupsi oleh penyelenggara negara bertentangan dengan Pancasila sila ....",
 ["kelima","pertama","kedua","ketiga","keempat"],
 "Korupsi merampas hak rakyat atas kesejahteraan sehingga bertentangan dengan sila kelima, Keadilan sosial bagi seluruh rakyat Indonesia."),
("TWK-938","Gerakan separatis bersenjata yang ingin memisahkan Papua dari NKRI dikenal dengan sebutan ....",
 ["OPM","RMS","DI/TII","PRRI","Permesta"],
 "Organisasi Papua Merdeka (OPM) adalah gerakan separatis bersenjata di Papua yang menentang kedaulatan NKRI."),
("TWK-939","Hingga kini larangan terhadap ajaran komunisme/Marxisme-Leninisme di Indonesia masih berlaku berdasarkan ....",
 ["TAP MPRS No. XXV/MPRS/1966","UU No. 5 Tahun 2018","UU No. 3 Tahun 2002","TAP MPR No. II/MPR/1978","UU No. 27 Tahun 1999"],
 "TAP MPRS No. XXV/MPRS/1966 tidak pernah dicabut sehingga larangan PKI dan ajaran komunisme tetap berlaku."),
("TWK-940","Pelajaran utama dari berbagai pemberontakan terhadap Pancasila adalah ....",
 ["Pancasila harus terus dipertahankan dan diamalkan agar tidak digantikan ideologi lain","setiap pemberontakan harus ditumpas dengan kekerasan","ideologi negara boleh diganti melalui referendum","pemerintah pusat harus memberi otonomi penuh kepada daerah","partai politik harus dibatasi jumlahnya"],
 "DI/TII, PRRI/Permesta, dan G30S/PKI menunjukkan Pancasila selalu menghadapi rongrongan sehingga harus dijaga dan diamalkan seluruh bangsa."),
# ===== UUD 1945 40 (941-980): kekuasaan kehakiman & pemilu =====
("TWK-941","Menurut Pasal 24 UUD 1945, kekuasaan kehakiman merupakan kekuasaan yang ....",
 ["merdeka","terbatas","sementara","bersyarat","di bawah presiden"],
 "Pasal 24 ayat (1) menegaskan kekuasaan kehakiman adalah kekuasaan yang merdeka untuk menyelenggarakan peradilan guna menegakkan hukum dan keadilan."),
("TWK-942","Kekuasaan kehakiman menurut UUD 1945 dilaksanakan oleh ....",
 ["Mahkamah Agung dan Mahkamah Konstitusi","Presiden dan DPR","Komisi Yudisial dan KPK","MPR dan DPD","Kejaksaan dan Kepolisian"],
 "Pasal 24 ayat (2) menentukan kekuasaan kehakiman dilakukan oleh Mahkamah Agung beserta badan peradilan di bawahnya dan Mahkamah Konstitusi."),
("TWK-943","Mahkamah Agung berwenang mengadili pada tingkat ....",
 ["kasasi","banding","pertama","praperadilan","arbitrase"],
 "Pasal 24A ayat (1) memberi wewenang kepada MA mengadili pada tingkat kasasi sebagai pengadilan negara tertinggi."),
("TWK-944","Pengujian peraturan perundang-undangan di bawah undang-undang terhadap undang-undang menjadi wewenang ....",
 ["Mahkamah Agung","Mahkamah Konstitusi","Komisi Yudisial","DPR","Presiden"],
 "Pasal 24A ayat (1): MA berwenang menguji peraturan perundang-undangan di bawah UU terhadap UU (hak uji materiil)."),
("TWK-945","Berikut ini badan peradilan yang berada di bawah Mahkamah Agung, kecuali ....",
 ["Mahkamah Konstitusi","peradilan umum","peradilan agama","peradilan militer","peradilan tata usaha negara"],
 "Di bawah MA ada peradilan umum, agama, militer, dan TUN; Mahkamah Konstitusi adalah pelaku kekuasaan kehakiman yang sejajar dengan MA."),
("TWK-946","Komisi Yudisial mempunyai wewenang ....",
 ["menjaga dan menegakkan kehormatan, keluhuran martabat, serta perilaku hakim","mengadili perkara pidana korupsi","menguji undang-undang terhadap UUD","menetapkan APBN","memilih presiden"],
 "Pasal 24B ayat (1): KY bersifat mandiri berwenang menjaga dan menegakkan kehormatan, keluhuran martabat, dan perilaku hakim."),
("TWK-947","Pengangkatan hakim agung diusulkan oleh ....",
 ["Komisi Yudisial","Presiden","DPR","MPR","Mahkamah Konstitusi"],
 "Pasal 24A ayat (3): calon hakim agung diusulkan Komisi Yudisial kepada DPR untuk mendapat persetujuan, lalu ditetapkan Presiden."),
("TWK-948","Anggota Komisi Yudisial diangkat dan diberhentikan oleh Presiden dengan persetujuan ....",
 ["DPR","MPR","DPD","MA","MK"],
 "Pasal 24B ayat (3): anggota KY diangkat dan diberhentikan oleh Presiden dengan persetujuan DPR."),
("TWK-949","Hakim konstitusi berjumlah sembilan orang yang diajukan masing-masing tiga orang oleh ....",
 ["MA, DPR, dan Presiden","MPR, DPR, dan DPD","Presiden, Wapres, dan MPR","KY, MA, dan DPR","DPR, DPD, dan Presiden"],
 "Pasal 24C ayat (3): tiga hakim diajukan MA, tiga oleh DPR, dan tiga oleh Presiden."),
("TWK-950","Pengujian undang-undang terhadap Undang-Undang Dasar menjadi wewenang ....",
 ["Mahkamah Konstitusi","Mahkamah Agung","Komisi Yudisial","DPR","MPR"],
 "Pasal 24C ayat (1): MK berwenang mengadili pada tingkat pertama dan terakhir yang putusannya final, termasuk menguji UU terhadap UUD."),
("TWK-951","Sengketa kewenangan lembaga negara yang kewenangannya diberikan oleh UUD diputus oleh ....",
 ["Mahkamah Konstitusi","Mahkamah Agung","Komisi Yudisial","MPR","Presiden"],
 "Pasal 24C ayat (1) memberi wewenang kepada MK memutus sengketa kewenangan lembaga negara yang kewenangannya diberikan UUD."),
("TWK-952","Lembaga yang berwenang memutus pembubaran partai politik adalah ....",
 ["Mahkamah Konstitusi","Mahkamah Agung","Komisi Pemilihan Umum","DPR","Kementerian Hukum"],
 "Pasal 24C ayat (1): MK berwenang memutus pembubaran partai politik."),
("TWK-953","Perselisihan tentang hasil pemilihan umum diputus oleh ....",
 ["Mahkamah Konstitusi","Mahkamah Agung","Bawaslu","DKPP","Pengadilan Negeri"],
 "Pasal 24C ayat (1): MK berwenang memutus perselisihan tentang hasil pemilu."),
("TWK-954","Mahkamah Konstitusi wajib memutus pendapat DPR bahwa Presiden melakukan pelanggaran hukum paling lama ....",
 ["90 hari","30 hari","60 hari","120 hari","14 hari"],
 "Pasal 24C ayat (2): MK wajib memberikan putusan atas pendapat DPR paling lama 90 hari setelah permintaan diterima."),
("TWK-955","Syarat-syarat untuk menjadi dan diberhentikan sebagai hakim menurut Pasal 25 UUD 1945 ditetapkan dengan ....",
 ["undang-undang","peraturan pemerintah","keputusan presiden","peraturan MA","tap MPR"],
 "Pasal 25: syarat menjadi hakim dan pemberhentiannya ditetapkan dengan undang-undang."),
("TWK-956","Pemilihan umum dilaksanakan dengan asas ....",
 ["langsung, umum, bebas, rahasia, jujur, dan adil","langsung, umum, bebas, dan rahasia","jujur, adil, dan terbuka","bebas, rahasia, dan cepat","umum, merata, dan berkeadilan"],
 "Pasal 22E ayat (1): pemilu dilaksanakan secara langsung, umum, bebas, rahasia, jujur, dan adil setiap lima tahun sekali."),
("TWK-957","Pemilihan umum dilaksanakan setiap ....",
 ["lima tahun sekali","empat tahun sekali","enam tahun sekali","tiga tahun sekali","tujuh tahun sekali"],
 "Pasal 22E ayat (1) menetapkan pemilu dilaksanakan setiap lima tahun sekali."),
("TWK-958","Melalui pemilihan umum, rakyat memilih ....",
 ["anggota DPR, DPD, Presiden dan Wakil Presiden, serta DPRD","menteri dan duta besar","hakim agung dan hakim konstitusi","gubernur dan bupati","pimpinan KPK dan KY"],
 "Pasal 22E ayat (2): pemilu diselenggarakan untuk memilih anggota DPR, DPD, Presiden dan Wakil Presiden, serta DPRD."),
("TWK-959","Peserta pemilihan umum untuk memilih anggota DPR dan DPRD adalah ....",
 ["partai politik","perseorangan","organisasi kemasyarakatan","serikat pekerja","organisasi keagamaan"],
 "Pasal 22E ayat (3): peserta pemilu untuk memilih anggota DPR dan DPRD adalah partai politik."),
("TWK-960","Peserta pemilihan umum untuk memilih anggota DPD adalah ....",
 ["perseorangan","partai politik","gabungan partai politik","organisasi masyarakat","calon independen partai"],
 "Pasal 22E ayat (4): peserta pemilu untuk memilih anggota DPD adalah perseorangan."),
]
Q += [
("TWK-961","Komisi Pemilihan Umum menurut UUD 1945 bersifat ....",
 ["nasional, tetap, dan mandiri","nasional, sementara, dan netral","daerah, tetap, dan independen","nasional, ad hoc, dan terbuka","tetap, rahasia, dan mandiri"],
 "Pasal 22E ayat (5): pemilu diselenggarakan oleh KPU yang bersifat nasional, tetap, dan mandiri."),
("TWK-962","Penyelenggaraan pemilihan umum saat ini diatur dalam ....",
 ["UU No. 7 Tahun 2017","UU No. 15 Tahun 2011","UU No. 42 Tahun 2008","UU No. 10 Tahun 2016","UU No. 23 Tahun 2014"],
 "UU No. 7 Tahun 2017 tentang Pemilihan Umum mengatur pemilu legislatif dan pemilu presiden secara serentak."),
("TWK-963","Lembaga yang bertugas mengawasi penyelenggaraan pemilihan umum adalah ....",
 ["Bawaslu","KPU","DKPP","MK","KY"],
 "Bawaslu (Badan Pengawas Pemilihan Umum) mengawasi seluruh tahapan penyelenggaraan pemilu."),
("TWK-964","Pemilihan umum pertama di Indonesia dilaksanakan pada tahun ....",
 ["1955","1950","1945","1965","1971"],
 "Pemilu pertama Indonesia dilaksanakan tahun 1955 untuk memilih anggota DPR dan Konstituante."),
("TWK-965","Pemilu 1955 dilaksanakan dua tahap, yaitu ....",
 ["29 September 1955 untuk DPR dan 15 Desember 1955 untuk Konstituante","15 Desember 1955 untuk DPR dan 29 September 1955 untuk Konstituante","pemilu DPR dan pemilu presiden","pemilu DPD dan DPRD","pemilu serentak nasional dan daerah"],
 "Tahap pertama 29 September 1955 memilih anggota DPR, tahap kedua 15 Desember 1955 memilih anggota Konstituante."),
("TWK-966","Pemilihan umum pertama pada masa Orde Baru dilaksanakan pada tahun ....",
 ["1971","1977","1982","1987","1999"],
 "Pemilu pertama Orde Baru dilaksanakan 5 Juli 1971 dan dimenangi Golkar."),
("TWK-967","Pemilihan presiden secara langsung oleh rakyat pertama kali dilaksanakan pada tahun ....",
 ["2004","1999","2009","2014","2019"],
 "Pilpres langsung pertama dilaksanakan 2004 sesuai UUD 1945 hasil amandemen (Pasal 6A)."),
("TWK-968","Partai politik peserta pemilu harus memenuhi ambang batas perolehan suara nasional sebesar ... untuk menempatkan anggotanya di DPR.",
 ["4%","3,5%","2,5%","5%","7%"],
 "UU No. 7 Tahun 2017 menetapkan parliamentary threshold 4% suara sah nasional."),
("TWK-969","Syarat pencalonan presiden dan wakil presiden oleh partai politik menurut UU Pemilu adalah ....",
 ["memperoleh 20% kursi DPR atau 25% suara sah nasional pada pemilu sebelumnya","memperoleh 10% kursi DPR","memperoleh 4% suara sah nasional","didukung minimal 3 partai politik","memperoleh 50% suara sah nasional"],
 "UU No. 7 Tahun 2017: presidential threshold 20% kursi DPR atau 25% suara sah nasional pemilu legislatif sebelumnya."),
("TWK-970","Pasangan calon presiden dan wakil presiden dinyatakan menang apabila ....",
 ["memperoleh lebih dari 50% suara dengan sedikitnya 20% suara di lebih dari setengah jumlah provinsi","memperoleh suara terbanyak secara nasional","memperoleh lebih dari 50% suara nasional","memperoleh 20% suara di seluruh provinsi","memperoleh suara terbanyak di Pulau Jawa"],
 "Pasal 6A ayat (3): menang bila meraih lebih dari 50% suara dengan minimal 20% suara di lebih dari separuh jumlah provinsi; jika tidak terpenuhi diadakan putaran kedua."),
("TWK-971","Masa jabatan Presiden dan Wakil Presiden menurut Pasal 7 UUD 1945 adalah ....",
 ["lima tahun dan dapat dipilih kembali hanya untuk satu kali masa jabatan","lima tahun dan dapat dipilih kembali tanpa batas","empat tahun dan dapat dipilih kembali satu kali","enam tahun untuk satu periode","tujuh tahun dan tidak dapat dipilih kembali"],
 "Pasal 7: Presiden dan Wakil Presiden memegang jabatan lima tahun dan sesudahnya dapat dipilih kembali dalam jabatan yang sama hanya untuk satu kali masa jabatan."),
("TWK-972","Apabila Presiden dan Wakil Presiden mangkat atau berhalangan tetap dalam waktu bersamaan, tugas kepresidenan dilaksanakan oleh ....",
 ["Menteri Dalam Negeri, Menteri Luar Negeri, dan Menteri Pertahanan secara bersama-sama","Ketua MPR","Ketua DPR","Ketua Mahkamah Agung","Panglima TNI"],
 "Pasal 8 ayat (3): ketiga menteri tersebut melaksanakan tugas kepresidenan hingga MPR memilih Presiden dan Wakil Presiden baru."),
("TWK-973","MPR wajib menyelenggarakan sidang untuk memilih Presiden dan Wakil Presiden baru paling lambat ... setelah keduanya berhalangan tetap.",
 ["30 hari","14 hari","60 hari","90 hari","7 hari"],
 "Pasal 8 ayat (3): selambat-lambatnya tiga puluh hari MPR menyelenggarakan sidang memilih Presiden dan Wakil Presiden."),
("TWK-974","Ketentuan mengenai jumlah anggota DPD adalah ....",
 ["jumlah tiap provinsi sama dan totalnya tidak lebih dari sepertiga jumlah anggota DPR","jumlah tiap provinsi berbeda dan totalnya sama dengan DPR","jumlah tiap provinsi sama dan totalnya setengah jumlah DPR","jumlah tiap provinsi berbeda dan totalnya sepertiga DPR","jumlah tiap provinsi sama dan totalnya dua pertiga DPR"],
 "Pasal 22D ayat (2): anggota DPD dari setiap provinsi jumlahnya sama dan jumlah seluruh anggota DPD tidak lebih dari sepertiga jumlah anggota DPR."),
("TWK-975","DPD dapat mengajukan rancangan undang-undang kepada DPR yang berkaitan dengan ....",
 ["otonomi daerah, hubungan pusat dan daerah, dan kepentingan daerah","APBN dan pajak","pertahanan dan keamanan","politik luar negeri","pendidikan nasional"],
 "Pasal 22D ayat (1): DPD dapat mengajukan RUU tentang otonomi daerah, hubungan pusat-daerah, pembentukan dan pemekaran daerah, serta pengelolaan sumber daya."),
("TWK-976","DPD memberikan pertimbangan kepada DPR atas rancangan undang-undang tentang ....",
 ["APBN, pajak, pendidikan, dan agama","pertahanan dan keamanan","politik luar negeri","kekuasaan kehakiman","kewarganegaraan"],
 "Pasal 22D ayat (2): DPD memberikan pertimbangan atas RUU APBN serta RUU yang berkaitan dengan pajak, pendidikan, dan agama."),
("TWK-977","Fungsi DPD dalam bidang pengawasan meliputi ....",
 ["pengawasan atas pelaksanaan undang-undang mengenai otonomi daerah dan kepentingan daerah","pengawasan terhadap kinerja presiden","pengawasan terhadap putusan pengadilan","pengawasan terhadap partai politik","pengawasan terhadap BUMN"],
 "Pasal 22D ayat (3): DPD mengawasi pelaksanaan UU mengenai otonomi daerah, pembentukan dan pemekaran daerah, hubungan pusat-daerah, serta pengelolaan sumber daya."),
("TWK-978","Majelis Permusyawaratan Rakyat terdiri atas ....",
 ["anggota DPR dan anggota DPD","anggota DPR dan utusan daerah","anggota DPR dan utusan golongan","presiden dan para menteri","anggota DPD dan DPRD"],
 "Pasal 2 ayat (1): MPR terdiri atas anggota DPR dan anggota DPD yang dipilih melalui pemilu."),
("TWK-979","Wewenang MPR menurut UUD 1945 adalah ....",
 ["mengubah dan menetapkan UUD serta melantik dan memberhentikan Presiden/Wakil Presiden","membentuk undang-undang bersama presiden","mengangkat duta besar","menetapkan APBN","mengadili perkara konstitusi"],
 "Pasal 3: MPR berwenang mengubah dan menetapkan UUD, melantik Presiden/Wakil Presiden, serta memberhentikan Presiden/Wakil Presiden dalam masa jabatannya."),
("TWK-980","Pemberhentian Presiden dalam masa jabatannya memerlukan tahapan ....",
 ["usul DPR, putusan Mahkamah Konstitusi, dan keputusan MPR","putusan MA dan persetujuan DPR","keputusan presiden dan persetujuan MPR","referendum rakyat","putusan pengadilan negeri"],
 "Pasal 7B: DPR mengusulkan, MK memeriksa dan memutus, lalu MPR memutuskan pemberhentian dengan kuorum dan suara tertentu."),
# ===== SEJARAH 30 (981-1010): kabinet demokrasi liberal & terpimpin =====
("TWK-981","Selama era demokrasi liberal (1950-1959), Indonesia mengalami pergantian kabinet sebanyak ....",
 ["7 kali","5 kali","6 kali","8 kali","9 kali"],
 "Era parlementer 1950-1959 diwarnai 7 kabinet: Natsir, Sukiman, Wilopo, Ali I, Burhanuddin Harahap, Ali II, dan Djuanda."),
("TWK-982","Kabinet pertama pada masa demokrasi liberal adalah ....",
 ["Kabinet Natsir","Kabinet Sukiman","Kabinet Wilopo","Kabinet Burhanuddin Harahap","Kabinet Djuanda"],
 "Kabinet Natsir (1950-1951) adalah kabinet pertama era demokrasi liberal dengan Mohammad Natsir dari Masyumi sebagai perdana menteri."),
("TWK-983","Salah satu program Kabinet Natsir adalah ....",
 ["meningkatkan keamanan dan ketertiban dalam negeri","menyelenggarakan Konferensi Asia-Afrika","membubarkan Uni Indonesia-Belanda","menasionalisasi perusahaan Belanda","menyelenggarakan pemilu 1955"],
 "Program Kabinet Natsir meliputi keamanan dan ketertiban, konsolidasi pemerintahan, penyempurnaan angkatan perang, pembangunan ekonomi rakyat, pendidikan, dan penyelesaian Irian Barat."),
("TWK-984","Kabinet Sukiman jatuh pada tahun 1952 karena ....",
 ["penandatanganan nota kesepahaman bantuan dengan Amerika Serikat","peristiwa Tanjung Morawa","kegagalan menyelenggarakan pemilu","pemberontakan PRRI","skandal korupsi menteri"],
 "Kabinet Sukiman dinilai condong ke blok Barat setelah menandatangani nota MSA dengan AS sehingga dijatuhkan parlemen."),
("TWK-985","Kabinet Wilopo jatuh pada tahun 1953 karena ....",
 ["peristiwa Tanjung Morawa di Sumatera Timur","penandatanganan nota MSA","kegagalan KAA","pemberontakan Permesta","konflik dengan presiden"],
 "Peristiwa Tanjung Morawa (16 Maret 1953), bentrokan petani dengan polisi soal tanah perkebunan, menjatuhkan Kabinet Wilopo."),
("TWK-986","Prestasi penting Kabinet Ali Sastroamidjojo I di bidang politik luar negeri adalah ....",
 ["menyelenggarakan Konferensi Asia-Afrika di Bandung","membubarkan Uni Indonesia-Belanda","menasionalisasi perusahaan Belanda","mengumumkan Deklarasi Djuanda","mengirim misi ke PBB"],
 "Kabinet Ali I (1953-1955) sukses menyelenggarakan KAA di Bandung pada 18-24 April 1955."),
("TWK-987","Konferensi Asia-Afrika diselenggarakan di Bandung pada ....",
 ["18-24 April 1955","18-24 April 1956","1-7 Mei 1955","29 September 1955","15 Desember 1955"],
 "KAA dihadiri 29 negara Asia-Afrika dan menghasilkan Dasasila Bandung."),
("TWK-988","Pemilihan umum tahun 1955 berhasil diselenggarakan pada masa kabinet ....",
 ["Burhanuddin Harahap","Ali Sastroamidjojo I","Sukiman","Wilopo","Djuanda"],
 "Kabinet Burhanuddin Harahap (1955-1956) menyelenggarakan pemilu DPR (29 September 1955) dan Konstituante (15 Desember 1955)."),
("TWK-989","Pada masa Kabinet Burhanuddin Harahap, Indonesia secara sepihak membubarkan ....",
 ["Uni Indonesia-Belanda","RIS","Konstituante","Dewan Nasional","APRIS"],
 "Tahun 1956 Indonesia membubarkan Uni Indonesia-Belanda sebagai protes atas kegagalan penyelesaian Irian Barat."),
("TWK-990","Kabinet Ali Sastroamidjojo II jatuh pada Maret 1957 karena ....",
 ["keluarnya Masyumi dari kabinet dan meluasnya pergolakan daerah","peristiwa Tanjung Morawa","penandatanganan nota MSA","gagal menyelenggarakan KAA","mosi tidak percaya soal ekonomi"],
 "Masyumi keluar dari kabinet dan pergolakan daerah (PRRI/Permesta) meluas sehingga Kabinet Ali II kehilangan dukungan."),
("TWK-991","Kabinet Djuanda (1957-1959) dikenal juga dengan sebutan ....",
 ["Kabinet Karya","Kabinet Gotong Royong","Kabinet Kerja","Kabinet Ampera","Kabinet Dwikora"],
 "Kabinet Djuanda disebut Kabinet Karya karena bersifat zaken (keahlian) dan tidak mewakili partai politik tertentu."),
("TWK-992","Deklarasi Djuanda yang menegaskan konsep negara kepulauan Indonesia dikeluarkan pada ....",
 ["13 Desember 1957","17 Agustus 1957","5 Juli 1959","18 April 1955","3 Mei 1964"],
 "Deklarasi Djuanda 13 Desember 1957 menjadi dasar konsep Wawasan Nusantara dan kemudian diakui dalam UNCLOS 1982."),
("TWK-993","Deklarasi Djuanda menegaskan bahwa ....",
 ["laut-laut di antara pulau-pulau Indonesia merupakan bagian yang tidak terpisahkan dari wilayah daratan","Indonesia menganut sistem federal","Irian Barat harus segera dikembalikan","perusahaan Belanda dinasionalisasi","Indonesia keluar dari PBB"],
 "Deklarasi ini menyatakan bahwa segala perairan di sekitar, di antara, dan yang menghubungkan pulau-pulau Indonesia adalah bagian integral wilayah RI."),
("TWK-994","Nasionalisasi perusahaan-perusahaan milik Belanda dilakukan pada masa ....",
 ["Kabinet Djuanda tahun 1957","Kabinet Natsir tahun 1950","Kabinet Ali I tahun 1955","Kabinet Kerja tahun 1960","Kabinet Ampera tahun 1966"],
 "Desember 1957, menyusul gagalnya perundingan Irian Barat, Indonesia menasionalisasi perusahaan-perusahaan Belanda."),
("TWK-995","Ciri utama sistem pemerintahan demokrasi liberal di Indonesia adalah ....",
 ["kabinet bertanggung jawab kepada parlemen dan mudah dijatuhkan melalui mosi tidak percaya","presiden memegang kekuasaan penuh","hanya ada satu partai politik","tidak ada pemilihan umum","tentara memegang pemerintahan"],
 "Sistem parlementer membuat kedudukan kabinet tidak stabil karena setiap saat dapat dijatuhkan DPR melalui mosi tidak percaya."),
("TWK-996","Masa demokrasi liberal berakhir dengan ....",
 ["Dekret Presiden 5 Juli 1959","Supersemar 1966","TAP MPRS XXV/1966","Proklamasi Kemerdekaan","Sumpah Pemuda"],
 "Dekret 5 Juli 1959 membubarkan Konstituante, memberlakukan kembali UUD 1945, dan mengakhiri demokrasi liberal."),
("TWK-997","Kabinet pertama pada masa demokrasi terpimpin adalah ....",
 ["Kabinet Kerja I","Kabinet Dwikora","Kabinet Ampera","Kabinet Karya","Kabinet Gotong Royong"],
 "Kabinet Kerja I (1959-1960) dipimpin langsung Presiden Soekarno sebagai perdana menteri."),
("TWK-998","Trikora diumumkan Presiden Soekarno di Yogyakarta pada ....",
 ["19 Desember 1961","3 Mei 1964","17 Agustus 1961","1 Oktober 1965","13 Desember 1957"],
 "Tri Komando Rakyat diumumkan 19 Desember 1961 untuk membebaskan Irian Barat dari Belanda."),
("TWK-999","Salah satu isi Trikora adalah ....",
 ["kibarkanlah Sang Saka Merah Putih di Irian Barat","ganyang Malaysia","bentuk Dewan Revolusi","nasionalisasi perusahaan asing","laksanakan pemilu"],
 "Isi Trikora: gagalkan pembentukan negara boneka Papua, kibarkan Merah Putih di Irian, dan bersiaplah mobilisasi umum."),
("TWK-1000","Dwikora diumumkan Presiden Soekarno pada 3 Mei 1964 sebagai komando ....",
 ["konfrontasi terhadap Malaysia","pembebasan Irian Barat","penumpasan PRRI","pemberantasan korupsi","pembangunan semesta"],
 "Dwi Komando Rakyat berisi perintah mengganyang Malaysia yang dinilai sebagai proyek neokolonialisme Inggris."),
("TWK-1001","Kabinet Dwikora dibentuk pada tahun ....",
 ["1964","1960","1962","1966","1959"],
 "Kabinet Dwikora I (1964-1966) dibentuk untuk melaksanakan konfrontasi terhadap Malaysia."),
("TWK-1002","Kabinet Dwikora yang Disempurnakan dibentuk pada Februari 1966 dengan tugas ....",
 ["menyelesaikan konfrontasi dan memulihkan ekonomi","melanjutkan konfrontasi Malaysia","menyelenggarakan pemilu","menyusun UUD baru","membubarkan MPRS"],
 "Kabinet Dwikora yang Disempurnakan berumur sangat pendek dan digantikan Kabinet Ampera setelah Supersemar."),
("TWK-1003","Kabinet Ampera (1966-1967) merupakan singkatan dari ....",
 ["Amanat Penderitaan Rakyat","Amanat Pembangunan Rakyat","Aksi Menentang Penjajah","Aliansi Masyarakat Rakyat","Amanat Persatuan Rakyat"],
 "Kabinet Ampera dibentuk pasca-Supersemar untuk melaksanakan amanat penderitaan rakyat."),
("TWK-1004","Tugas pokok Kabinet Ampera dikenal dengan sebutan ....",
 ["Dwi Dharma","Tri Dharma","Panca Dharma","Eka Dharma","Catur Dharma"],
 "Dwi Dharma Kabinet Ampera: menciptakan stabilitas politik dan stabilitas ekonomi."),
("TWK-1005","Pada masa demokrasi terpimpin, Manipol-Usdek ditetapkan sebagai ....",
 ["Garis-Garis Besar Haluan Negara","UUD baru","ideologi tertutup","program kabinet","dasar negara"],
 "Manipol-Usdek (UUD 1945, Sosialisme Indonesia, Demokrasi Terpimpin, Ekonomi Terpimpin, Kepribadian Indonesia) dijadikan haluan negara."),
("TWK-1006","Landasan konstitusional masa demokrasi terpimpin adalah ....",
 ["UUD 1945 hasil Dekret Presiden 5 Juli 1959","UUDS 1950","Konstitusi RIS","Piagam Jakarta","UUD 1945 yang diamandemen"],
 "Dekret 5 Juli 1959 memberlakukan kembali UUD 1945 sebagai konstitusi negara."),
("TWK-1007","Lembaga legislatif pada masa demokrasi terpimpin adalah ....",
 ["DPR Gotong Royong","DPR hasil pemilu 1955","DPR Orde Baru","Konstituante","DPD"],
 "Setelah membubarkan DPR hasil pemilu 1955, Soekarno membentuk DPR-GR dengan anggota yang diangkat presiden."),
("TWK-1008","Masa demokrasi terpimpin berakhir pada tahun ....",
 ["1966","1965","1967","1959","1971"],
 "Terbitnya Supersemar 11 Maret 1966 menandai peralihan kekuasaan dan berakhirnya demokrasi terpimpin menuju Orde Baru."),
("TWK-1009","Salah satu penyimpangan demokrasi pada masa demokrasi terpimpin adalah ....",
 ["pembubaran DPR hasil pemilu dan pengangkatan presiden seumur hidup","penyelenggaraan pemilu yang bebas","penguatan peran parlemen","pembatasan masa jabatan presiden","kebebasan pers"],
 "Soekarno membubarkan DPR hasil pemilu 1955 dan diangkat menjadi presiden seumur hidup (TAP MPRS III/1963), mematikan demokrasi."),
("TWK-1010","Perbedaan mendasar demokrasi liberal dan demokrasi terpimpin terletak pada ....",
 ["kedudukan presiden dan peran parlemen dalam sistem pemerintahan","jumlah partai politik","wilayah negara","dasar negara","lambang negara"],
 "Demokrasi liberal menempatkan parlemen dominan dengan presiden seremonial, sedangkan demokrasi terpimpin memusatkan kekuasaan pada presiden."),
]
Q += [
# ===== NKRI 30 (1011-1040): otonomi daerah & pemekaran =====
("TWK-1011","Menurut Pasal 18 UUD 1945, Negara Kesatuan Republik Indonesia dibagi atas daerah ....",
 ["provinsi serta kabupaten dan kota","negara bagian","distrik dan keresidenan","kewedanaan dan kecamatan","desa dan kelurahan"],
 "Pasal 18 ayat (1): NKRI dibagi atas daerah-daerah provinsi dan daerah provinsi dibagi atas kabupaten dan kota."),
("TWK-1012","Pemerintahan daerah provinsi, kabupaten, dan kota terdiri atas ....",
 ["kepala daerah dan DPRD","gubernur dan wali kota","bupati dan camat","DPR dan DPD","camat dan lurah"],
 "Pasal 18 ayat (3): pemerintahan daerah terdiri atas kepala daerah dan DPRD yang dipilih secara demokratis."),
("TWK-1013","Pemerintah daerah menjalankan otonomi seluas-luasnya, kecuali urusan yang menjadi kewenangan pemerintah pusat, yaitu ....",
 ["politik luar negeri, pertahanan, keamanan, yustisi, moneter dan fiskal nasional, serta agama","pendidikan, kesehatan, dan pekerjaan umum","pertanian, perikanan, dan kehutanan","perdagangan dan perindustrian","perhubungan dan komunikasi"],
 "UU No. 23 Tahun 2014 menetapkan enam urusan absolut pemerintah pusat yang tidak dapat diotonomikan."),
("TWK-1014","Berikut ini urusan pemerintahan yang menjadi kewenangan mutlak pemerintah pusat, kecuali ....",
 ["pendidikan","politik luar negeri","pertahanan","keamanan","agama"],
 "Pendidikan adalah urusan konkuren yang dibagi antara pusat dan daerah, sedangkan empat lainnya urusan absolut pusat."),
("TWK-1015","Pengakuan negara terhadap satuan pemerintahan daerah yang bersifat khusus atau istimewa diatur dalam ....",
 ["Pasal 18B UUD 1945","Pasal 18 UUD 1945","Pasal 18A UUD 1945","Pasal 25A UUD 1945","Pasal 33 UUD 1945"],
 "Pasal 18B ayat (1): negara mengakui dan menghormati satuan-satuan pemerintahan daerah yang bersifat khusus atau istimewa."),
("TWK-1016","Status kekhususan DKI Jakarta sebagai ibu kota negara diatur dalam ....",
 ["UU No. 29 Tahun 2007","UU No. 23 Tahun 2014","UU No. 11 Tahun 2006","UU No. 21 Tahun 2001","UU No. 13 Tahun 2012"],
 "UU No. 29 Tahun 2007 mengatur pemerintahan Provinsi DKI Jakarta sebagai ibu kota NKRI."),
("TWK-1017","Keistimewaan Aceh sebagai daerah istimewa diatur dalam ....",
 ["UU No. 11 Tahun 2006","UU No. 21 Tahun 2001","UU No. 13 Tahun 2012","UU No. 29 Tahun 2007","UU No. 23 Tahun 2014"],
 "UU No. 11 Tahun 2006 tentang Pemerintahan Aceh adalah tindak lanjut MoU Helsinki 2005."),
("TWK-1018","MoU Helsinki yang mengakhiri konflik Aceh ditandatangani pada ....",
 ["15 Agustus 2005","15 Agustus 2004","11 Maret 1966","20 Desember 2001","12 Februari 2002"],
 "Nota kesepahaman antara pemerintah Indonesia dan GAM ditandatangani di Helsinki, Finlandia, pada 15 Agustus 2005."),
("TWK-1019","Otonomi khusus bagi Provinsi Papua diatur dalam ....",
 ["UU No. 21 Tahun 2001","UU No. 11 Tahun 2006","UU No. 13 Tahun 2012","UU No. 23 Tahun 2014","UU No. 29 Tahun 2007"],
 "UU No. 21 Tahun 2001 memberikan otonomi khusus bagi Papua dalam kerangka NKRI."),
("TWK-1020","Salah satu keistimewaan Daerah Istimewa Yogyakarta adalah ....",
 ["Sultan Hamengku Buwono ditetapkan sebagai gubernur","memiliki mata uang sendiri","memiliki angkatan bersenjata sendiri","tidak mengikuti pemilu nasional","bebas dari pajak nasional"],
 "UU No. 13 Tahun 2012 menetapkan Sultan Hamengku Buwono sebagai gubernur dan Adipati Paku Alam sebagai wakil gubernur DIY."),
("TWK-1021","Penyelenggaraan pemerintahan daerah saat ini diatur dalam ....",
 ["UU No. 23 Tahun 2014","UU No. 32 Tahun 2004","UU No. 22 Tahun 1999","UU No. 5 Tahun 1974","UU No. 1 Tahun 2015"],
 "UU No. 23 Tahun 2014 tentang Pemerintahan Daerah menggantikan UU No. 32 Tahun 2004."),
("TWK-1022","Anggota DPRD dipilih melalui ....",
 ["pemilihan umum","pengangkatan gubernur","musyawarah adat","penunjukan presiden","pemilihan oleh kepala daerah"],
 "Pasal 22E ayat (2): anggota DPRD dipilih melalui pemilihan umum setiap lima tahun sekali."),
("TWK-1023","Pemilihan kepala daerah secara langsung oleh rakyat mulai dilaksanakan berdasarkan ....",
 ["UU No. 32 Tahun 2004","UU No. 22 Tahun 1999","UU No. 23 Tahun 2014","UU No. 5 Tahun 1974","UUD 1945 sebelum amandemen"],
 "UU No. 32 Tahun 2004 memperkenalkan pilkada langsung; sebelumnya kepala daerah dipilih oleh DPRD."),
("TWK-1024","Pembentukan provinsi atau kabupaten/kota baru dari pemekaran daerah induk disebut ....",
 ["daerah otonom baru","daerah istimewa","daerah khusus","daerah tertinggal","daerah perbatasan"],
 "Daerah otonom baru (DOB) adalah daerah hasil pemekaran yang memiliki pemerintahan daerah sendiri."),
("TWK-1025","Syarat pembentukan daerah otonom baru meliputi ....",
 ["syarat administratif, teknis, dan fisik kewilayahan","persetujuan PBB","referendum rakyat","dukungan militer","pengesahan Mahkamah Konstitusi"],
 "PP No. 78 Tahun 2007 mengatur syarat administratif, teknis, dan fisik kewilayahan bagi pembentukan DOB."),
("TWK-1026","Kebijakan penghentian sementara pembentukan daerah otonom baru disebut ....",
 ["moratorium pemekaran","desentralisasi fiskal","dekonsentrasi","tugas pembantuan","otonomi khusus"],
 "Moratorium pemekaran diberlakukan pemerintah untuk menata dan mengevaluasi DOB yang sudah ada."),
("TWK-1027","Provinsi Banten merupakan hasil pemekaran dari Provinsi ....",
 ["Jawa Barat","Jawa Tengah","Jawa Timur","DKI Jakarta","Lampung"],
 "Banten dibentuk tahun 2000 sebagai pemekaran dari Jawa Barat."),
("TWK-1028","Provinsi Kepulauan Bangka Belitung merupakan pemekaran dari Provinsi ....",
 ["Sumatera Selatan","Sumatera Utara","Jambi","Lampung","Riau"],
 "Bangka Belitung dibentuk tahun 2000 sebagai pemekaran dari Sumatera Selatan."),
("TWK-1029","Provinsi Kepulauan Riau merupakan pemekaran dari Provinsi ....",
 ["Riau","Sumatera Barat","Jambi","Sumatera Utara","Kepulauan Bangka Belitung"],
 "Kepulauan Riau dibentuk berdasarkan UU No. 25 Tahun 2002 sebagai pemekaran dari Riau."),
("TWK-1030","Provinsi Gorontalo merupakan pemekaran dari Provinsi ....",
 ["Sulawesi Utara","Sulawesi Selatan","Sulawesi Tengah","Sulawesi Tenggara","Maluku Utara"],
 "Gorontalo dibentuk tahun 2000 sebagai pemekaran dari Sulawesi Utara."),
("TWK-1031","Provinsi Sulawesi Barat merupakan pemekaran dari Provinsi ....",
 ["Sulawesi Selatan","Sulawesi Tengah","Sulawesi Utara","Sulawesi Tenggara","Gorontalo"],
 "Sulawesi Barat dibentuk tahun 2004 sebagai pemekaran dari Sulawesi Selatan."),
("TWK-1032","Provinsi Maluku Utara merupakan pemekaran dari Provinsi ....",
 ["Maluku","Papua","Sulawesi Utara","Nusa Tenggara Timur","Papua Barat"],
 "Maluku Utara dibentuk tahun 1999 sebagai pemekaran dari Maluku."),
("TWK-1033","Provinsi Kalimantan Utara yang dibentuk tahun 2012 merupakan pemekaran dari Provinsi ....",
 ["Kalimantan Timur","Kalimantan Barat","Kalimantan Selatan","Kalimantan Tengah","Sabah"],
 "Kalimantan Utara (UU No. 20 Tahun 2012) menjadi provinsi ke-34 sebagai pemekaran dari Kalimantan Timur."),
("TWK-1034","Provinsi Papua Barat merupakan pemekaran dari Provinsi ....",
 ["Papua","Maluku","Maluku Utara","Papua Selatan","Nusa Tenggara Timur"],
 "Papua Barat dibentuk berdasarkan UU No. 45 Tahun 1999 sebagai pemekaran dari Papua."),
("TWK-1035","Pada tahun 2022 Indonesia menambah empat provinsi baru di Papua, yaitu ....",
 ["Papua Selatan, Papua Tengah, Papua Pegunungan, dan Papua Barat Daya","Papua Utara, Papua Timur, Papua Barat, dan Papua Selatan","Papua Pegunungan, Papua Lembah, Papua Pesisir, dan Papua Kepulauan","Papua Tengah, Papua Utara, Papua Barat Daya, dan Papua Timur","Papua Selatan, Papua Utara, Papua Barat, dan Papua Tengah"],
 "UU No. 14, 15, 16, dan 29 Tahun 2022 membentuk empat provinsi baru sehingga jumlah provinsi menjadi 38."),
("TWK-1036","Jumlah provinsi di Indonesia saat ini adalah ....",
 ["38","34","33","37","40"],
 "Setelah penambahan empat provinsi di Papua tahun 2022, Indonesia memiliki 38 provinsi."),
("TWK-1037","Salah satu dampak negatif pemekaran daerah yang tidak terkendali adalah ....",
 ["bertambahnya beban anggaran negara dan pemerintahan yang tidak efisien","meningkatnya pelayanan publik","berkurangnya korupsi","mempercepat pembangunan daerah","meningkatnya partisipasi politik"],
 "Pemekaran yang dipaksakan membebani APBN/APBD untuk belanja birokrasi tanpa diimbangi peningkatan pelayanan."),
("TWK-1038","Tujuan utama pelaksanaan otonomi daerah adalah ....",
 ["mendekatkan pelayanan publik kepada masyarakat dan mempercepat kesejahteraan daerah","memperkuat kekuasaan pemerintah pusat","mengurangi jumlah pegawai negeri","menyeragamkan seluruh daerah","menghapus DPRD"],
 "Otonomi daerah bertujuan meningkatkan efisiensi pelayanan, pemberdayaan masyarakat, dan percepatan kesejahteraan sesuai potensi daerah."),
("TWK-1039","Pemerintahan desa diatur dalam ....",
 ["UU No. 6 Tahun 2014","UU No. 23 Tahun 2014","UU No. 32 Tahun 2004","UU No. 22 Tahun 1999","UU No. 5 Tahun 1979"],
 "UU No. 6 Tahun 2014 tentang Desa mengakui dan menghormati desa beserta hak asal-usulnya."),
("TWK-1040","Dana desa bersumber dari ....",
 ["APBN yang disalurkan melalui APBD kabupaten/kota","APBD provinsi","kas desa","sumbangan masyarakat","pinjaman luar negeri"],
 "Dana desa dialokasikan dari APBN dan disalurkan melalui APBD kabupaten/kota untuk membiayai pembangunan dan pemberdayaan desa."),
# ===== BAHASA INDONESIA 20 (1041-1060): kata depan/partikel/imbuhan =====
("TWK-1041","Penulisan kata depan yang menunjukkan tempat dengan tepat adalah ....",
 ["di rumah","dirumah","di-rumah","dirum ah","diRumah"],
 "Kata depan di, ke, dan dari ditulis terpisah dari kata yang mengikutinya jika menunjukkan tempat atau arah."),
("TWK-1042","Penulisan imbuhan di- yang tepat adalah ....",
 ["dimakan","di makan","di-makan","diMak an","di_makan"],
 "Imbuhan di- ditulis serangkai dengan kata dasarnya, misalnya dimakan, ditulis, dibaca."),
("TWK-1043","Penulisan kata depan yang tepat adalah ....",
 ["ke sana","kesana","ke-sana","kes ana","keSana"],
 "Kata depan ke yang menunjukkan arah ditulis terpisah: ke sana, ke pasar, ke Jakarta."),
("TWK-1044","Penulisan kata tanya berikut yang tepat adalah ....",
 ["ke mana","kemana","ke-mana","kem ana","keMana"],
 "Kata mana adalah kata ganti tanya sehingga ke ditulis terpisah: ke mana."),
("TWK-1045","Kata daripada yang menyatakan perbandingan ditulis ....",
 ["serangkai","terpisah","dengan tanda hubung","dengan huruf kapital","dengan apostrof"],
 "Kata daripada sebagai kata hubung perbandingan ditulis serangkai, misalnya lebih baik daripada."),
("TWK-1046","Penulisan partikel -lah yang tepat adalah ....",
 ["bacalah","baca lah","baca-lah","bac alah","bacaLah"],
 "Partikel -lah, -kah, dan -tah ditulis serangkai dengan kata yang mendahuluinya."),
("TWK-1047","Penulisan partikel -kah yang tepat adalah ....",
 ["apakah","apa kah","apa-kah","ap akah","apaKah"],
 "Partikel -kah ditulis serangkai: apakah, siapakah, bagaimanakah."),
("TWK-1048","Penulisan partikel pun yang tepat adalah ....",
 ["dia pun datang","diapun datang","dia-pun datang","di apun datang","diapundatang"],
 "Partikel pun ditulis terpisah dari kata yang mendahuluinya, kecuali pada kata hubung tertentu seperti walaupun dan meskipun."),
("TWK-1049","Kata hubung berikut yang ditulis serangkai adalah ....",
 ["walaupun","walau pun","wala upun","wa lau pun","walaup un"],
 "Walaupun, meskipun, bagaimanapun, sekalipun, dan sungguhpun ditulis serangkai sebagai satu kata."),
("TWK-1050","Bentuk berimbuhan me- dari kata sapu adalah ....",
 ["menyapu","mesapu","mensapu","menyapui","memsapu"],
 "Kata berawalan s mengalami peluluhan menjadi ny-: menyapu, menyanyi, menyikat."),
("TWK-1051","Bentuk berimbuhan me- dari kata pukul adalah ....",
 ["memukul","mepukul","menpukul","menyukul","mempukul"],
 "Kata berawalan p luluh menjadi m-: memukul, memakai, memotong."),
("TWK-1052","Bentuk berimbuhan me- dari kata tari adalah ....",
 ["menari","metari","mentari","menyari","mementari"],
 "Kata berawalan t luluh menjadi n-: menari, menulis, menutup."),
("TWK-1053","Bentuk berimbuhan me- dari kata cat adalah ....",
 ["mengecat","menyat","mecat","mencat","mengcat"],
 "Kata bersuku satu tidak mengalami peluluhan sehingga menjadi mengecat, mengepel, mengelem."),
("TWK-1054","Penulisan kata ganti -ku, -mu, -nya yang tepat adalah ....",
 ["bukuku","buku ku","buku-ku","buk uku","bukuKu"],
 "Kata ganti -ku, -mu, -nya ditulis serangkai dengan kata yang mendahuluinya."),
("TWK-1055","Penulisan bentuk terikat antar- yang tepat adalah ....",
 ["antarpulau","antar pulau","antar-pulau","antarPulau","antar pulau-pulau"],
 "Bentuk terikat antar-, pra-, pasca-, tuna-, dan swa- ditulis serangkai dengan kata yang mengikutinya."),
("TWK-1056","Penulisan kata berikut yang tepat adalah ....",
 ["pascasarjana","pasca sarjana","pasca-sarjana","pascaSarjana","pasca sarjana"],
 "Bentuk terikat pasca- ditulis serangkai: pascasarjana, pascapanen."),
("TWK-1057","Penulisan kata berikut yang tepat adalah ....",
 ["prasejarah","pra sejarah","pra-sejarah","praSejarah","pra sejarah"],
 "Bentuk terikat pra- ditulis serangkai: prasejarah, prasarana."),
("TWK-1058","Penulisan kata ulang berimbuhan yang tepat adalah ....",
 ["berlari-lari","berlari lari","ber-lari-lari","berlarilari","ber lari-lari"],
 "Kata ulang berimbuhan ditulis dengan tanda hubung di antara pengulangan kata dasarnya."),
("TWK-1059","Penulisan kata turunan berikut yang tepat adalah ....",
 ["mempertanggungjawabkan","mempertanggung jawabkan","mempertanggung-jawabkan","mem pertanggungjawabkan","mempertanggung jawab kan"],
 "Awalan dan akhiran ditulis serangkai dengan kata dasarnya, termasuk pada kata majemuk: mempertanggungjawabkan."),
("TWK-1060","Penulisan singkatan gelar yang tepat adalah ....",
 ["S.H.","SH","Sh.","s.h.","S-H"],
 "Singkatan nama orang, gelar, dan jabatan ditulis dengan huruf kapital diikuti tanda titik: S.H., M.Si., S.E."),
# ===== BELA NEGARA 20 (1061-1080): konflik sosial, terorisme, radikalisme =====
("TWK-1061","Undang-undang yang mengatur pertahanan negara adalah ....",
 ["UU No. 3 Tahun 2002","UU No. 23 Tahun 2019","UU No. 34 Tahun 2004","UU No. 2 Tahun 2002","UU No. 5 Tahun 2018"],
 "UU No. 3 Tahun 2002 tentang Pertahanan Negara mengatur keikutsertaan warga negara dalam bela negara."),
("TWK-1062","Komponen utama pertahanan negara adalah ....",
 ["TNI","Komcad","Polri","warga negara","ASN"],
 "UU No. 3 Tahun 2002 menetapkan TNI sebagai komponen utama pertahanan negara."),
("TWK-1063","Komponen cadangan pertahanan negara terdiri atas ....",
 ["warga negara yang disiapkan untuk dikerahkan melalui mobilisasi","prajurit TNI aktif","anggota Polri aktif","pegawai negeri sipil","anggota DPR"],
 "Komponen cadangan adalah warga negara, sumber daya alam, buatan, serta sarana prasarana yang disiapkan untuk dikerahkan."),
("TWK-1064","Pembentukan Komponen Cadangan diatur dalam ....",
 ["UU No. 23 Tahun 2019","UU No. 3 Tahun 2002","UU No. 34 Tahun 2004","UU No. 5 Tahun 2018","UU No. 7 Tahun 2012"],
 "UU No. 23 Tahun 2019 tentang Pengelolaan Sumber Daya Nasional untuk Pertahanan Negara menjadi dasar pembentukan Komcad."),
("TWK-1065","Penyebaran paham yang bertentangan dengan Pancasila termasuk ancaman ....",
 ["nonmiliter di bidang ideologi","militer bersenjata","nonmiliter di bidang ekonomi","militer tidak bersenjata","hibrida bersenjata"],
 "Ancaman nonmiliter meliputi bidang ideologi, politik, ekonomi, sosial budaya, dan teknologi informasi."),
("TWK-1066","Menurut UU No. 5 Tahun 2018, terorisme adalah ....",
 ["perbuatan yang menggunakan kekerasan atau ancaman kekerasan yang menimbulkan suasana teror atau ketakutan","unjuk rasa yang anarkis","tindak pidana korupsi","pelanggaran lalu lintas","sengketa tanah"],
 "UU No. 5 Tahun 2018 mendefinisikan terorisme sebagai perbuatan dengan kekerasan/ancaman kekerasan yang menimbulkan teror, korban massal, atau kerusakan objek vital."),
("TWK-1067","Pemberantasan tindak pidana terorisme saat ini diatur dalam ....",
 ["UU No. 5 Tahun 2018","UU No. 15 Tahun 2003","UU No. 3 Tahun 2002","UU No. 7 Tahun 2012","UU No. 23 Tahun 2019"],
 "UU No. 5 Tahun 2018 adalah perubahan atas UU No. 15 Tahun 2003 tentang Pemberantasan Tindak Pidana Terorisme."),
("TWK-1068","Lembaga yang mengoordinasikan penanggulangan terorisme di Indonesia adalah ....",
 ["BNPT","Densus 88","BIN","KPK","Komnas HAM"],
 "Badan Nasional Penanggulangan Terorisme (BNPT) dibentuk tahun 2010 untuk mengoordinasikan pencegahan dan penanggulangan terorisme."),
("TWK-1069","Detasemen khusus Polri yang menangani pemberantasan terorisme adalah ....",
 ["Densus 88 Antiteror","Brimob","Gegana","Propam","Reskrim"],
 "Densus 88 AT Polri adalah satuan khusus penindakan terhadap jaringan terorisme."),
("TWK-1070","Tragedi Bom Bali I yang menjadi momentum penguatan pemberantasan terorisme terjadi pada ....",
 ["12 Oktober 2002","1 Oktober 2005","17 Juli 2009","14 Januari 2016","13 Mei 2018"],
 "Bom Bali I pada 12 Oktober 2002 menewaskan 202 orang dan mendorong lahirnya Perpu antiterorisme."),
("TWK-1071","Program pembinaan untuk mengembalikan pemahaman narapidana terorisme agar meninggalkan kekerasan disebut ....",
 ["deradikalisasi","kontra-radikalisasi","rehabilitasi medis","reintegrasi sosial","amnesti"],
 "Deradikalisasi adalah program pembinaan bagi pelaku terorisme agar meninggalkan paham kekerasan."),
("TWK-1072","Upaya pencegahan penyebaran paham radikal sebelum terjadi tindak pidana disebut ....",
 ["kontra-radikalisasi","deradikalisasi","demiliterisasi","dekonsentrasi","dekriminalisasi"],
 "Kontra-radikalisasi meliputi kontra-narasi, kontra-propaganda, dan penanaman nilai kebangsaan."),
("TWK-1073","Salah satu ciri paham radikal adalah ....",
 ["menghalalkan kekerasan untuk mencapai tujuan politik","menghormati perbedaan pendapat","menjunjung musyawarah","menghargai keberagaman","menaati hukum"],
 "Radikalisme ditandai sikap intoleran, eksklusif, takfiri, dan menghalalkan kekerasan demi tujuan politik."),
("TWK-1074","Upaya menangkal radikalisme melalui penguatan pemahaman keagamaan yang damai disebut ....",
 ["moderasi beragama","sekularisasi","liberalisasi agama","sinkretisme","pluralisme ekstrem"],
 "Moderasi beragama menekankan cara beragama yang tidak ekstrem, toleran, dan menghargai keberagaman."),
("TWK-1075","Penanganan konflik sosial di Indonesia diatur dalam ....",
 ["UU No. 7 Tahun 2012","UU No. 5 Tahun 2018","UU No. 3 Tahun 2002","UU No. 23 Tahun 2019","UU No. 7 Tahun 2017"],
 "UU No. 7 Tahun 2012 tentang Penanganan Konflik Sosial mengatur pencegahan, penghentian, dan pemulihan pascakonflik."),
("TWK-1076","Konflik sosial menurut UU No. 7 Tahun 2012 adalah ....",
 ["perseteruan dan/atau benturan fisik dengan kekerasan antara dua kelompok masyarakat atau lebih","perbedaan pendapat dalam rapat","persaingan usaha yang sehat","sengketa perdata","demonstrasi damai"],
 "Konflik sosial adalah perseteruan/kekerasan fisik antar kelompok yang mengganggu stabilitas dan pembangunan."),
("TWK-1077","Perjanjian Malino I yang mengakhiri konflik Poso ditandatangani pada ....",
 ["20 Desember 2001","12 Februari 2002","15 Agustus 2005","11 Maret 1966","7 Agustus 1949"],
 "Deklarasi Malino I pada 20 Desember 2001 mengakhiri konflik horizontal di Poso, Sulawesi Tengah."),
("TWK-1078","Perjanjian Malino II yang mengakhiri konflik Maluku ditandatangani pada ....",
 ["12 Februari 2002","20 Desember 2001","15 Agustus 2005","11 Maret 1966","30 September 1965"],
 "Deklarasi Malino II pada 12 Februari 2002 mengakhiri konflik horizontal di Maluku."),
("TWK-1079","Tahap pemulihan pascakonflik sosial meliputi ....",
 ["rekonsiliasi, rehabilitasi, dan rekonstruksi","penangkapan dan penahanan","mobilisasi militer","pemekaran wilayah","transmigrasi"],
 "UU No. 7 Tahun 2012 menetapkan pemulihan pascakonflik melalui rekonsiliasi, rehabilitasi, dan rekonstruksi."),
("TWK-1080","Peran warga negara dalam mencegah terorisme antara lain ....",
 ["melaporkan hal mencurigakan kepada aparat dan tidak menyebarluaskan konten radikal","membentuk laskar bersenjata","melakukan sweeping","menyebarluaskan video kekerasan","menghakimi pelaku"],
 "Bela negara di era modern diwujudkan dengan kewaspadaan, literasi digital, dan kerja sama dengan aparat, bukan main hakim sendiri."),
]

random.seed(7)
items = []
for (qid, q, opts, ex) in Q:
    order = list(range(5))
    random.shuffle(order)
    new_opts = [opts[i] for i in order]
    a = order.index(0)
    items.append({"id": qid, "q": q, "opts": new_opts, "a": a, "ex": ex})

# sanity
assert len(items) == 180, len(items)
ids = [x["id"] for x in items]
assert len(set(ids)) == 180
for x in items:
    assert len(x["opts"]) == 5 and 0 <= x["a"] <= 4 and x["q"] and x["ex"]

with open("/home/hatch/workspace/siasn/js/data/twk_b7.js", "w") as f:
    f.write("window.QB_TWK_B7 = ")
    f.write(json.dumps(items, ensure_ascii=False))
    f.write(";\n")

# distribusi jawaban
from collections import Counter
print("distribusi a:", Counter(x["a"] for x in items))
print("OK - 180 soal ditulis")
